"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var alterarCliente_1 = __importDefault(require("../empresa/cliente/alterarCliente"));
var cadastroCliente_1 = __importDefault(require("../empresa/cliente/cadastroCliente"));
var deletarCliente_1 = __importDefault(require("../empresa/cliente/deletarCliente"));
var listagemClientes_1 = __importDefault(require("../empresa/cliente/listagemClientes"));
var consumoCliente_1 = __importDefault(require("../empresa/consumo/consumoCliente"));
var listar5MaisConsumo_1 = __importDefault(require("../empresa/consumo/listar5MaisConsumo"));
var listarConsumoGen_1 = __importDefault(require("../empresa/consumo/listarConsumoGen"));
var listarMaiorConsumo_1 = __importDefault(require("../empresa/consumo/listarMaiorConsumo"));
var listarMenorConsumo_1 = __importDefault(require("../empresa/consumo/listarMenorConsumo"));
var listarServicoCliente_1 = __importDefault(require("../empresa/consumo/listarServicoCliente"));
var listarServMais_1 = __importDefault(require("../empresa/consumo/listarServMais"));
var prodMaisConsumido_1 = __importDefault(require("../empresa/consumo/prodMaisConsumido"));
var listarGenero_1 = __importDefault(require("../empresa/listarGenero"));
var altearProduto_1 = __importDefault(require("../empresa/produto/altearProduto"));
var cadastroProduto_1 = __importDefault(require("../empresa/produto/cadastroProduto"));
var listagemProdutos_1 = __importDefault(require("../empresa/produto/listagemProdutos"));
var alterarServico_1 = __importDefault(require("../empresa/servico/alterarServico"));
var cadastroServico_1 = __importDefault(require("../empresa/servico/cadastroServico"));
var deletarServico_1 = __importDefault(require("../empresa/servico/deletarServico"));
var listarServico_1 = __importDefault(require("../empresa/servico/listarServico"));
var entrada_1 = __importDefault(require("../io/entrada"));
var cliente_1 = __importDefault(require("../model/cliente"));
var cpf_1 = __importDefault(require("../model/cpf"));
var empresa_1 = __importDefault(require("../model/empresa"));
var produto_1 = __importDefault(require("../model/produto"));
var servico_1 = __importDefault(require("../model/servico"));
var empresa = new empresa_1.default();
var execucao = true;
var cliente = new cliente_1.default("Antonio Marcelo", "Marcelo", new cpf_1.default("0", "13/04/1998"), "M");
var cliente1 = new cliente_1.default("Bruna Dias", "Bruna", new cpf_1.default("1", "13/04/1998"), "F");
var cliente2 = new cliente_1.default("Emerton Ribeiro", "Emerton", new cpf_1.default("2", "13/04/1998"), "M");
var cliente3 = new cliente_1.default("Raquel Silva", "Raquel", new cpf_1.default("3", "13/04/1998"), "F");
var cliente4 = new cliente_1.default("Gabriel Coutinho", "Gabriel", new cpf_1.default("4", "13/04/1998"), "M");
var cliente5 = new cliente_1.default("Dionisio Leão", "Dionisio", new cpf_1.default("5", "13/04/1998"), "M");
var cliente6 = new cliente_1.default("Carla Brito", "Carla", new cpf_1.default("6", "13/04/1998"), "F");
var cliente7 = new cliente_1.default("Leticia Almeida", "Leticia", new cpf_1.default("7", "13/04/1998"), "F");
var cliente8 = new cliente_1.default("Andre Ribeiro", "Andre", new cpf_1.default("8", "13/04/1998"), "M");
var cliente9 = new cliente_1.default("Rodrigo Ribas", "Rodrigo", new cpf_1.default("9", "13/04/1998"), "M");
var cliente10 = new cliente_1.default("Cleber Santos", "Cleber", new cpf_1.default("10", '22/02/2012)'), 'M');
var cliente11 = new cliente_1.default("Antonio Marcos", "Marcos", new cpf_1.default('11', '11/11/2011'), 'M');
var cliente12 = new cliente_1.default('Conceição Alves', 'Conceição', new cpf_1.default('12', '12/12/2012'), 'F');
var cliente13 = new cliente_1.default('Maria Conceição', 'Maria', new cpf_1.default('13', '05/06/1998'), 'F');
var cliente14 = new cliente_1.default('Marcos Monroe', 'Marcos', new cpf_1.default('14', '23/08/1995'), 'M');
var cliente15 = new cliente_1.default('Renata Lemos', 'Renata', new cpf_1.default('15', '29/05/1990'), 'F');
var cliente16 = new cliente_1.default('Vitor Manuel', 'Vitor', new cpf_1.default('16', '16/04/2001'), 'M');
var cliente17 = new cliente_1.default('Marcelo Eduardo', 'Marcelo', new cpf_1.default('17', '05/05/1995'), 'M');
var cliente18 = new cliente_1.default('Claudia Moreira', 'Claudia', new cpf_1.default('18', '18/02/2002'), 'F');
var cliente19 = new cliente_1.default('Maria Aparecida', 'Maria', new cpf_1.default('19', '19/07/1887'), 'F');
var cliente20 = new cliente_1.default('Marcio Francisco', 'Marcio', new cpf_1.default('20', '20/05/2000'), 'M');
var cliente21 = new cliente_1.default('Lis Silva', 'Lis', new cpf_1.default('21', '21/02/2005'), 'F');
var cliente22 = new cliente_1.default('Theo Brito', 'Theo', new cpf_1.default('22', '22/06/2006'), 'M');
var cliente23 = new cliente_1.default('Agatha Barbosa', 'Agatha', new cpf_1.default('23', '23/08/2007'), 'F');
var cliente24 = new cliente_1.default('Aurora Rodrigues', 'Aurora', new cpf_1.default('24', '24/09/2008'), 'F');
var cliente25 = new cliente_1.default('Guilherme Filho', 'Guilherme', new cpf_1.default('25', '25/08/2007'), 'M');
var cliente26 = new cliente_1.default('Jose Soares', 'Jose', new cpf_1.default('26', '26/08/1880'), 'M');
var cliente27 = new cliente_1.default('Miguel Alves', 'Miguel', new cpf_1.default('27', '27/02/2009'), 'M');
var cliente28 = new cliente_1.default('Maria Clara', 'Maria', new cpf_1.default('28', '28/10/2010'), 'F');
var cliente29 = new cliente_1.default('Julia Gibim', 'Julia', new cpf_1.default('29', '29/02/2001'), 'F');
var servico = new servico_1.default("Corte Feminino", 60, 1);
var servico1 = new servico_1.default("Unha", 15, 2);
var servico2 = new servico_1.default("Chapinha", 18, 3);
var servico3 = new servico_1.default("Progressiva", 200, 4);
var servico4 = new servico_1.default("Tintura capilar", 50, 5);
var servico5 = new servico_1.default("Manicure", 30, 6);
var servico6 = new servico_1.default("Pedicure", 30, 7);
var servico7 = new servico_1.default("Dsign de sobrancelhas", 33, 8);
var servico8 = new servico_1.default("Remoção de rugas", 130, 9);
var servico9 = new servico_1.default("Remoção de manchas na pele", 150, 10);
var servico10 = new servico_1.default("Aplicação de botox", 800, 11);
var servico11 = new servico_1.default("Tratamento para emagrecimento", 950, 12);
var servico12 = new servico_1.default("Corte masculino", 25, 13);
var servico13 = new servico_1.default("Barba", 15, 14);
var servico14 = new servico_1.default("Tratamento para queda de cabelo", 68, 15);
var produto = new produto_1.default("Gel", 15, 1);
var produto1 = new produto_1.default("Pomada", 20, 2);
var produto2 = new produto_1.default("Condicionador", 25, 3);
var produto3 = new produto_1.default("Creme", 30, 4);
var produto4 = new produto_1.default("Esmalte", 5, 5);
var produto5 = new produto_1.default("Shampoo", 30, 6);
var produto6 = new produto_1.default("Mascara de hidratação", 35, 7);
var produto7 = new produto_1.default("Tinta de cabelo", 15, 8);
var produto8 = new produto_1.default("Oléo de hidratação", 10, 9);
var produto9 = new produto_1.default("Spray fixador", 20, 10);
var produto10 = new produto_1.default("Sérum reparador", 50, 11);
var produto11 = new produto_1.default("Queratína", 23, 12);
var produto12 = new produto_1.default("Ampolas para nutríção", 6, 13);
var produto13 = new produto_1.default("Pomada modeladora", 18, 14);
var produto14 = new produto_1.default("Acetona", 12, 15);
var produto15 = new produto_1.default("Algodão", 8, 16);
var produto16 = new produto_1.default("Leave in", 42, 17);
var produto17 = new produto_1.default("Protetor térmico", 60, 18);
var produto18 = new produto_1.default("Touca", 5, 19);
var produto19 = new produto_1.default("Peruca", 50, 20);
cliente.addProduto(produto);
cliente.addProduto(produto);
cliente.addProduto(produto2);
cliente.addProduto(produto9);
cliente.addServicos(servico12);
cliente.addServicos(servico12);
cliente.addServicos(servico13);
cliente1.addProduto(produto3);
cliente1.addProduto(produto4);
cliente1.addProduto(produto13);
cliente1.addProduto(produto17);
cliente1.addServicos(servico);
cliente1.addServicos(servico10);
cliente3.addProduto(produto6);
cliente3.addProduto(produto16);
cliente3.addProduto(produto17);
cliente3.addProduto(produto10);
cliente3.addServicos(servico);
cliente3.addServicos(servico3);
cliente3.addServicos(servico11);
cliente4.addProduto(produto4);
cliente4.addProduto(produto2);
cliente4.addProduto(produto19);
cliente4.addServicos(servico);
cliente4.addServicos(servico10);
cliente4.addServicos(servico2);
cliente10.addServicos(servico11);
cliente10.addServicos(servico12);
cliente10.addProduto(produto16);
cliente24.addProduto(produto);
cliente24.addProduto(produto15);
cliente24.addProduto(produto18);
cliente24.addServicos(servico5);
empresa.getCliente.push(cliente);
empresa.getCliente.push(cliente1);
empresa.getCliente.push(cliente2);
empresa.getCliente.push(cliente3);
empresa.getCliente.push(cliente4);
empresa.getCliente.push(cliente5);
empresa.getCliente.push(cliente6);
empresa.getCliente.push(cliente7);
empresa.getCliente.push(cliente8);
empresa.getCliente.push(cliente9);
empresa.getCliente.push(cliente10);
empresa.getCliente.push(cliente11);
empresa.getCliente.push(cliente12);
empresa.getCliente.push(cliente13);
empresa.getCliente.push(cliente14);
empresa.getCliente.push(cliente15);
empresa.getCliente.push(cliente16);
empresa.getCliente.push(cliente17);
empresa.getCliente.push(cliente18);
empresa.getCliente.push(cliente19);
empresa.getCliente.push(cliente20);
empresa.getCliente.push(cliente21);
empresa.getCliente.push(cliente22);
empresa.getCliente.push(cliente23);
empresa.getCliente.push(cliente24);
empresa.getCliente.push(cliente25);
empresa.getCliente.push(cliente26);
empresa.getCliente.push(cliente27);
empresa.getCliente.push(cliente28);
empresa.getCliente.push(cliente29);
empresa.getServicos.push(servico);
empresa.getServicos.push(servico1);
empresa.getServicos.push(servico2);
empresa.getServicos.push(servico3);
empresa.getServicos.push(servico4);
empresa.getServicos.push(servico5);
empresa.getServicos.push(servico6);
empresa.getServicos.push(servico7);
empresa.getServicos.push(servico8);
empresa.getServicos.push(servico9);
empresa.getServicos.push(servico10);
empresa.getServicos.push(servico11);
empresa.getServicos.push(servico12);
empresa.getServicos.push(servico13);
empresa.getServicos.push(servico14);
empresa.getProdutos.push(produto);
empresa.getProdutos.push(produto1);
empresa.getProdutos.push(produto2);
empresa.getProdutos.push(produto3);
empresa.getProdutos.push(produto4);
empresa.getProdutos.push(produto5);
empresa.getProdutos.push(produto6);
empresa.getProdutos.push(produto7);
empresa.getProdutos.push(produto8);
empresa.getProdutos.push(produto9);
empresa.getProdutos.push(produto10);
empresa.getProdutos.push(produto11);
empresa.getProdutos.push(produto12);
empresa.getProdutos.push(produto13);
empresa.getProdutos.push(produto14);
empresa.getProdutos.push(produto15);
empresa.getProdutos.push(produto16);
empresa.getProdutos.push(produto17);
empresa.getProdutos.push(produto18);
empresa.getProdutos.push(produto19);
while (execucao) {
    console.log("Op\u00E7\u00F5es:");
    console.log("1 - Cadastrar cliente");
    console.log("2 - Listar todos os clientes");
    console.log("3 - cadastrar produtos");
    console.log("4 - Listar todos os Produtos:");
    console.log("5 - cadastrar servi\u00E7os:");
    console.log("6 - Listar todos os servi\u00E7os:");
    console.log("7 - Adicionar Servi\u00E7os/Produtos: ");
    console.log("8 - Listar Servi\u00E7os do Cliente: ");
    console.log("9 - Excluir Cliente: ");
    console.log("10 - Excluir Servi\u00E7o: ");
    console.log("11 - Editar Dados do Cliente: ");
    console.log("12 - Editar Servi\u00E7os: ");
    console.log("13 - Editar Produtos: ");
    console.log("14 - Listar Genero: ");
    console.log("15 - Listar 5 mais em valor: ");
    console.log("16 - Listar consumo por g\u00EAnero: ");
    console.log("17 - Listar 10 mais em quantidade: ");
    console.log("18 - Listar 10 menos em quantidade: ");
    console.log("19 - Listar produto mais consumido: ");
    console.log("20 - Listar servi\u00E7o mais consumido: ");
    console.log("0 - Sair");
    var entrada = new entrada_1.default();
    var opcao = entrada.receberNumero("Por favor, escolha uma op\u00E7\u00E3o: ");
    switch (opcao) {
        case 1:
            var cadastro = new cadastroCliente_1.default(empresa.getCliente);
            cadastro.cadastrar();
            break;
        case 2:
            var listagem = new listagemClientes_1.default(empresa.getCliente);
            listagem.listar();
            break;
        case 3:
            var Produto_1 = new cadastroProduto_1.default(empresa.getProdutos);
            Produto_1.cadastrar();
            break;
        case 4:
            var listagemProdutos = new listagemProdutos_1.default(empresa.getProdutos);
            listagemProdutos.listar();
            break;
        case 5:
            var servico_2 = new cadastroServico_1.default(empresa.getServicos);
            servico_2.cadastrar();
            break;
        case 6:
            var listagemServico = new listarServico_1.default(empresa.getServicos);
            listagemServico.listar();
            break;
        case 7:
            var consumoCliente = new consumoCliente_1.default(empresa);
            consumoCliente.cadastrar();
            break;
        case 8:
            var listarServicoCliente = new listarServicoCliente_1.default(empresa.getCliente);
            listarServicoCliente.listar();
            break;
        case 9:
            var deletaCliente = new deletarCliente_1.default(empresa.getCliente);
            deletaCliente.deletar();
            break;
        case 10:
            var deletaServico = new deletarServico_1.default(empresa.getServicos);
            deletaServico.deletar();
            break;
        case 11:
            var editarCliente = new alterarCliente_1.default(empresa.getCliente);
            editarCliente.alterar();
            break;
        case 12:
            var editarServico = new alterarServico_1.default(empresa.getServicos);
            editarServico.alterar();
            break;
        case 13:
            var editaProduto = new altearProduto_1.default(empresa.getProdutos);
            editaProduto.alterar();
            break;
        case 14:
            var listarGenero = new listarGenero_1.default(empresa.getCliente);
            listarGenero.listar();
            break;
        case 15:
            var listar5Mais = new listar5MaisConsumo_1.default(empresa.getCliente);
            listar5Mais.listar();
            break;
        case 16:
            var listarConsumoGen = new listarConsumoGen_1.default(empresa.getCliente);
            listarConsumoGen.listar();
            break;
        case 17:
            var listar10Mais = new listarMaiorConsumo_1.default(empresa.getCliente);
            listar10Mais.listar();
            break;
        case 18:
            var listar10Menos = new listarMenorConsumo_1.default(empresa.getCliente);
            listar10Menos.listar();
            break;
        case 19:
            var listarProdMais = new prodMaisConsumido_1.default(empresa.getCliente);
            listarProdMais.listar();
            break;
        case 20:
            var listarServMais = new listarServMais_1.default(empresa.getCliente);
            listarServMais.listar();
            break;
        case 0:
            execucao = false;
            console.log("At\u00E9 mais");
            break;
        default:
            console.log("Opera\u00E7\u00E3o n\u00E3o entendida :(");
    }
}
